### ISSUE TITLE
Crates.io Release?

### ISSUE THREAD

**Issue by Lokathor** [maia-s/sdl3-sys-rs#1]
I just wanted to open an issue for tracking when a crates.io release might be available.

Obviously the generator is a work in progress, and the SDL3 C library itself isn't even officially available yet, but I thought it would be good to have a place to keep any notes about the progress.

**Comment by maia-s** [comment]
My current plan for the first new prerelease is to get all the modules generated and building without errors, and then make a release of that. There's no major features missing to make this happen now, mostly I just have to add some "known defines" (the generator rejects defines it doesn't know, defined or not), handle some special cases, and fix at least one bug.

That will be missing building and linking SDL itself, but it should be enough for people to start playing with and I think it's better to get something out ASAP. After the first prerelease I'll add build/link of the SDL library and make another prerelease with that.

The most significant features missing from the generator right now are #define'd functions and inline functions. Some of those are important, but I think the first prerelease can do without them. The inline functions in particular I think are unlikely for users to want to use from Rust. Currently those are emitted as external functions, but that should be harmless – trying to use them would result in a link error.

**Comment by Lokathor** [comment]
for SDL2, some of the C pre-processor macros i just wrote as a `const fn` for usage in rust, mostly it was the stuff for getting info from pixel format values.

**Comment by maia-s** [comment]
Yeah, I may do that, at least initially. The generator should be able to handle them if I add type annotations for known function-like macros tho. Some of them may be able to be inferred too, like with constant value macros.

As an alternative I could emit them as Rust macros to preserve the flexible typing, but I don't think that would gain much for how they're used in SDL.

**Comment by maia-s** [comment]
All of the modules generate now, except for a few skipped ones (egl and opengl system headers). Some of the modules have errors tho

**Comment by Lokathor** [comment]
I honestly don't think that egl and gl should be generated by default, we've got solutions for that in the rust ecosystem already.

a cargo feature for it might be appropriate, but it would clog the docs and such with a lot of extra stuff most people won't want if it's on by default.

**Comment by maia-s** [comment]
Yeah, I agree.

**Comment by maia-s** [comment]
Everything generates and builds without errors now, so it's technically ready to go for the first new prerelease. I'll add a readme to the crate and publish it tomorrow, and maybe fix some of the missing defined functions first.

**Comment by maia-s** [comment]
It's published!

**Comment by maia-s** [comment]
@Lokathor How do you feel about having a separate crate for building SDL from source? It'd be an implementation detail, depended on by sys when requested

Pros:
- It'd save a 10MB download for users who want to use a pre-existing build
- It could have features specific to configuring the built SDL without cluttering the sys crate
- Source crate version could be the same as the SDL version

Cons:
- It's an extra crate (easy to automate tho)

**Comment by Lokathor** [comment]
Two crates is good, and using an existing sdl3 is neat, but one possible problem is if the existing sdl3 (from eg a package manager) is *older* than the one that sdl3-sys is generated with.

So, sdl3-sys would need to detect the provided sdl3 version and use cfg or something to only allow in the correct api level.

**Comment by maia-s** [comment]
For stable versions SDL has traditionally been fully backwards compatible, only adding new symbols and never making backwards incompatible changes to the API or ABI. I don't think backwards compatibility was ever an issue for SDL 2. Software like Steam relies on this (for Linux games, Steam recommends that games don't ship their own version of SDL and instead relies on the one shipped by Steam, which is updated from time to time). Assuming this continues to be true, the worst that could happen with stable SDL is that a built crate fails to link because it requires a symbol from a newer SDL version than it linked to.

Custom builds of SDL could break that assumption, but I don't think there's a way for us to deal with that unless we want to require build signatures or build a database of valid hashes for libraries that may be linked to. I don't think that's desirable or practical (except for when using the SDL framework on mac, which has to be signed anyway)

For prereleases and dev releases of SDL (`3.<odd-number>.x` versions are dev releases according to SDL's versioning scheme), it's definitely an issue. The `SDL_GetVersion` and `SDL_GetRevision` functions should be stable, so we *could* link a small executable to the external library and run that to check the version/revision in the build script, but the version doesn't include revision information and the revision is an arbitrary string that can be overridden at build time, e.g. by a linux distro, so it's not reliable. In any case this wouldn't work when cross compiling, and we have no way of knowing that the library that's going to be used when executing the built binary is the same as that used at link time. In fact, for Linux games heading to Steam, it probably won't be.

Anyway, I think until the first stable version of SDL 3 is available, maybe it's better if sdl3-sys only supports building and linking our own provided version of SDL. Maybe do that for dev releases later on too.

**Comment by Lokathor** [comment]
Yeah, a generic link error would occur. I suppose I was hoping the cfg could make a clearer error sooner in the build about trying to import a symbol that's not defined. It's maybe not worth the extra work.

**Comment by maia-s** [comment]
It wouldn't be hard to check the version in the build script with a small built executable, so we could do that if it wouldn't break cross compiling. I'm not sure if linking an older stable version of SDL should be an error though, if they don't actually use symbols from a newer version. Maybe it could be a warning. Can a build script from a dependency like sdl3-sys print a warning that will be visible when building the top level crate?

**Comment by maia-s** [comment]
or there could be a feature to enable the check and error

**Comment by Lokathor** [comment]
>  if they don't actually use symbols from a newer version

This is the most compelling point to me. I think we should just allow it and it's up to the sys crate user to not call what's not actually in the linked version.

**Comment by maia-s** [comment]
Yeah, let's go with that.

**Comment by maia-s** [comment]
I found a flaw with the separate crate for source plan and posted about it in #2

**Comment by maia-s** [comment]
All the inline functions and function-like defines are generated now, and constants that were missing are generated now too. Many defines use inferred types that may need to be patched tho

**Comment by maia-s** [comment]
I've published sdl3-sys 0.0.10 for SDL 3.1.3-preview!
