### ISSUE TITLE
Direct use of `bool` in FFI is not advised

### ISSUE THREAD

**Issue by Lokathor** [maia-s/sdl3-sys-rs#4]
I double checked with the community discord before posting this, but basically rust's `bool` type shouldn't appear in FFI signatures directly, because different C ABIs treat it differently, and not all C compilers even have a real "bool" type.

I believe we should have all signatures go back to using `bool` updated to be a newtype over a `u32`.

**Comment by maia-s** [comment]
I also checked with the community discord before deciding to use rust bool for this, and I was told it was fine in this case.
- SDL asserts that `sizeof(bool) == 1` at compile time for all targets in `SDL_stdinc.h`. If this assertion fails SDL won't compile.
- If C99/C23 bool is used and is size 1, Rust's bool is binary compatible, using bit patterns 0x01 for true and 0x00 for false
- Even if stdbool isn't used for some platform, SDL always uses its own defines for true and false instead of relying on type coercion on returns, so we should still be able to rely on getting only 0x01 or 0x00 from SDL

**Comment by revmischa** [comment]
I'm sure the current setup is fine because we're mostly just returning bools from C into rust and then passing them around rust. There's a few places where they are passed from rust as args to C functions but I can't really imagine how they will be distorted.

**Comment by Lokathor** [comment]
Alright, if people don't see a point to it

**Comment by maia-s** [comment]
I do think this is important, but unless I've been misinformed, bool works for this particular case, and bool is a better user experience.

The part about SDL asserting bool to be size 1 was crucial for this to work, so I don't think the information you were given conflicts with the information I was given if they didn't know about that part.

If I'm wrong, please reopen this issue.
